#!@shell@

export PATH="@binPath@:${PATH}"

read -r -d '' HELP_MSG << EOM
NAME
    secrets

SYNOPSIS
    secrets [COMMON OPTIONS] [--edit|--decrypt] --machine HOST --service SERVICE --secret-name NAME
    secrets [COMMON OPTIONS] --re-encrypt --machine HOST --service SERVICE
    secrets [COMMON OPTIONS] --re-encrypt-all --machine HOST

DESCRIPTION
    Secrets is the command made for nix repos to get rid of the secret.nix when
    you are using agenix. Secrets must be used with secrets host-info roles to work.

    By default, secrets are stored in machines/\${HOST}/secrets/service/
    if this directory exists, unless otherwise specified.

COMMON OPTIONS
    -f, --secrets-folder PATH
        Optional. Specify the location where secrets are saved.

    -v, --vm
        Optional. Use vmVariant for the target machine.

    -V, --verbose
        Optional. Produce more verbose log messages.

    -D, --debug
        Optional. Show the full bash trace for this script.

    -h, --help
        Optional. Show this help message.

MODE OPTIONS
    -e, --edit
        Edit the secret.
        This is the default mode.

    -d, --decrypt
        Decrypt and print the secret.

    -r, --re-encrypt
        Re-encrypt the secret.

    -a, --re-encrypt-all
        Re-encrypt all secrets for the specified host.

TARGET OPTIONS
    -m, --machine HOST
        Target machine.

    -s, --service SERVICE
        Target service.

    -n, --secret-name NAME
        Target secret name.

EXAMPLES
    secrets --machine geth-01.tsw-tyo1.lido.mainnet --service cachix-deploy --secret-name token
    secrets --vm --machine geth-01.tsw-tyo1.lido.mainnet --service cachix-deploy --secret-name token
    secrets --re-encrypt --machine geth-01.tsw-tyo1.lido.mainnet --service cachix-deploy
    secrets --re-encrypt-all --machine geth-01.tsw-tyo1.lido.mainnet
EOM

set -euo pipefail

function nix_eval_secrets() {
  target="${1}"
  shift
  machineName="${machine}"
  if [[ "${machineType}" == 'vm' ]]; then
    machineName="vm-${machineName}"
  fi
  nix eval "${@}" ".#nixosConfigurations.\"${machineName}\".config.secrets.${target}"
}

function agenix_wrapper() {
  # Secrets folder is available in the secrets object in Nix.
  if [[ -z "${secretsFolder}" ]]; then
    local secretsFolder=$(
      nix_eval_secrets services."${service}".encryptedSecretDir --raw \
        | sed -r 's#/nix/store/[a-z0-9]+-(source|secrets)/?##'
    )
    # If path has no subfolders it must be that of defaults.
    if [[ -z "${secretsFolder}" ]]; then
      local secretsFolder="types/${machineType}/secrets"
    fi
  fi
  # The Agenix secrets definition file is generated by Nix.
  export rulesFile="$(nix_eval_secrets "services.${service}.nix-file" --raw)"
  if [[ -z "${rulesFile}" ]]; then
    echo "ERROR: No Agenix rules file found!" >&2
    exit 1
  fi
  # Support providiing custom paths to Age identity files.
  if [[ -n "${AGE_IDENTITIES}" ]]; then
    export agenixArgs="-i $(echo "${AGE_IDENTITIES}" | sed -z '$ s/\n$//' | tr '\n' ' ' | sed -e 's/ / -i /g')"
  fi
  # Show what is being executed to the user.
  if [[ "${verbose}" == 'true' ]]; then
    agenixArgs="-v ${agenixArgs}"
    cat >&2 <<EOF
{
  cd ${secretsFolder}/${service};
  ln -s ${rulesFile} secrets.nix;
  agenix ${agenixArgs} "\$@";
  unlink secrets.nix;
}
EOF
  fi

  pushd "${secretsFolder}/${service}" >/dev/null

  # Required due to: https://github.com/yaxitech/ragenix/issues/160
  ln -fs "${rulesFile}" secrets.nix
  trap "unlink ${PWD}/secrets.nix" RETURN

  agenix ${agenixArgs} "${@}";
  popd >/dev/null
}

machine=""
service=""
secretName=""
debug=false
verbose=false
machineType=server
decrypt=false
reEncrypt=false
reEncryptAll=false
secretsFolder=""

if ! parsedFlags=$(
  getopt \
  -o 'f:m:s:n:vdraVDh' \
  -l 'secrets-folder:,machine:,service:,secret-name:,vm,decrypt,re-encrypt,re-encrypt-all,verbose,debug,help' \
  -n 'secrets' -- "$@"
); then
  echo "ERROR: failed to parse options" >&2
  echo "${HELP_MSG}" >&2
  exit 2
fi
eval set -- "${parsedFlags}"

while true; do
  case "${1}" in
    -f|--secrets-folder)    secretsFolder="${2}"; shift 2;;
    -m|--machine)           machine="${2}";       shift 2;;
    -s|--service)           service="${2}";       shift 2;;
    -n|--secret-name)       secretName="${2}";    shift 2;;
    -v|--vm)                machineType=vm;       shift;;
    -d|--decrypt)           decrypt=true;         shift;;
    -r|--re-encrypt)        reEncrypt=true;       shift;;
    -a|--re-encrypt-all)    reEncryptAll=true;    shift;;
    -V|--verbose)           verbose=true;         shift;;
    -D|--debug)             debug=true;           shift;;
    -h|--help)              echo "${HELP_MSG}";   exit 0;;
    --)                     shift;                break;;
    *)                      echo "ERROR: unknown option $1" >&2; echo "${HELP_MSG}"; exit 1;;
  esac
done

# Enable debug bash tracing.
if [[ "${debug}" == true ]]; then
    set -x
fi

if [[ "${reEncryptAll}" == true && -z "${machine}" ]]; then
  echo "ERROR: you must specify machine" >&2; echo "${HELP_MSG}"; exit 1
elif [[ "${reEncrypt}" == true && (-z "${machine}" || -z "${service}") ]]; then
  echo "ERROR: you must specify machine and service" >&2; echo "${HELP_MSG}"; exit 1
elif [[ "${reEncrypt}" == false && "${reEncryptAll}" == false && (-z "${machine}" || -z "${service}" || -z "${secretName}") ]]; then
  echo "ERROR: you must specify machine, service, and secret" >&2; echo "${HELP_MSG}"; exit 1
fi

if [[ "${reEncryptAll}" == true ]]; then
  for service in $(nix_eval_secrets "services" --apply builtins.attrNames --json | jq -r '.[]'); do
    echo "Re-encripting secrets for: ${service}"
    agenix_wrapper -r
  done
else
  if [[ "${reEncrypt}" == true ]]; then
    agenix_wrapper -r
  elif [[ "${decrypt}" == true ]]; then
    EDITOR=cat agenix_wrapper -e "${secretName}.age" | grep -v 'skipping re-encryption'
  else
    agenix_wrapper -e "${secretName}.age"
  fi
fi
